# Site settings (Mainly used for SEO Plugin)
title: Jonathan Southern's Portfolio and Blog
description: Jonathan Southern's personal experiences and skills written down.
url: www.jonathan-southern.com
author: Jonathan Southern
twitter:
  username: JonathanSouth17
  card: summary
social:
  name: Jonathan Southern
  links:
    - https://www.linkedin.com/in/jonathan-southern-772b4b135/
logo: ../assets/img/myAvatar.svg
lang: en_us
email: your-email@example.com
baseurl: "/"  

# Build settings
markdown: kramdown
include: ['_pages']

# Permalinks
permalink: /blog/:title

# Other
port: 7000 

#Plugins
plugins:
  - jekyll-seo-tag