# Site settings (Mainly used for SEO Plugin)
title: Jonathan Southern's Portfolio and Blog
description: Jonathan Southern's personal experiences and skills written down.
url: www.jonathan-southern.me
author: Jonathan Southern
logo: ../assets/img/myAvatar.svg
lang: en_us
baseurl: "/"  

# Build settings
markdown: kramdown
include: ['_pages']

# Permalinks
permalink: /blog/:title

# Other
port: 7000 

#Plugins
plugins:
  - jekyll-seo-tag