# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    folder: '_posts/'
    editor:
      preview: false
    fields:
      - { label: "Featured Image", name: 'thumbnail', widget: "image" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'select',
          options: ['Frontend', 'Backend', 'Testing', 'Personal']
        }
  - name: 'projects'
    label: 'Projects'
    folder: '_projects/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Featured Image", name: 'thumbnail', widget: "image"}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'select',
          options: ['Personal', 'Professional']
        }